---

- hosts: all
  become: true
  tasks:


  - name: update repo index
    tags: always
    apt: 
      update_cache: yes
      


  - name: install the apache2 package
    tags: apache, apache2
    apt:
      name: apache2
      state: latest

  - name: copy html file for site.
    tags: apache, apache2
    copy: 
      src: default_index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstation
  become: true
  tasks:
   - name: install unzip
     package: 
       name: unzip


   - name: install terraform
     unarchive:
        src: https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root 
